# Generated by Django 5.1.2 on 2024-10-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='logo',
            field=models.ImageField(default='characters/default.jpg', upload_to='characters/'),
        ),
        migrations.AlterField(
            model_name='characterslist',
            name='background',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='characterslist',
            name='class_character',
        ),
        migrations.AlterField(
            model_name='characterslist',
            name='class_defense',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='characterslist',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='characterslist',
            name='race',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.race'),
        ),
        migrations.AlterField(
            model_name='characterslist',
            name='speed',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('game_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.classes')),
            ],
        ),
        migrations.AddField(
            model_name='characterslist',
            name='class_character',
            field=models.ManyToManyField(to='character.characterclass'),
        ),
    ]
