# Generated by Django 5.1.2 on 2024-10-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_alter_character_logo_alter_characterslist_background_and_more'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterslist',
            name='background',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='characterslist',
            name='race',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.race'),
        ),
    ]
